# vim: set filetype=sh :

. ${CUSTOM_PROFILE}/dotfiles/profile_update

if [ -z "$CUSTOM_PROFILE" ]; then
	echo "Set CUSTOM_PROFILE variable to location of GIT repo. Eg. /home/username/profile.git."
	echo "Not loading customizations."
else

	if [ ! -f ~/.profile_update ]; then
		updateProfile
	else
		checkUpdateProfile
	fi

	. ${CUSTOM_PROFILE}/dotfiles/profile
fi

# vim: set syntax=sh:
