# vim: set filetype=sh :

# only run in interactive shell
case $- in
    *i*)    # interactive shell
	# Update profile from github.
	. ${CUSTOM_PROFILE}/dotfiles/profile_update $CUSTOM_PROFILE

	# Custom profile stuff
	. ${CUSTOM_PROFILE}/dotfiles/profile $CUSTOM_PROFILE


	;;
    *)
    ;;
esac

# vim: set syntax=sh:
